### ISSUE TITLE
Holding your sword in your offhand slot bug

### ISSUE THREAD

**Issue by DanielWaeraasUran** [Ziroxis/souls-awakening#47]
Holding your sword in the offhand slot causes your sword to both be in your arm and trigger the zanpakuto overlay

![Image](https://github.com/user-attachments/assets/be84e3a4-c363-4283-9cfb-d136b98f545f)

**Comment by Beosti** [comment]
fixed! Also made it so different types of zanpakuto also appear like what they are (the wakizashi one)
